
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s26/team02-s26-07
owner: ucsb-cs156-s26
repo_name: team02-s26-07
pull_requests: [{"author":{"id":"MDQ6VXNlcjcwNDg0MDk5","is_bot":false,"login":"Coragon42","name":"Coragon42"},"headRefName":"Coragon42-CopyFiles","number":65,"title":"ey - copy files from team01 for RecommendationRequests","url":"https://github.com/ucsb-cs156-s26/team02-s26-07/pull/65"},{"author":{"id":"U_kgDOCNoU5Q","is_bot":false,"login":"Alexander-Reyes9","name":"AlexanderReyes99"},"headRefName":"ar-UCSBOrganization-fixtures","number":64,"title":"Add fixtures for UCSBOrganization","url":"https://github.com/ucsb-cs156-s26/team02-s26-07/pull/64"},{"author":{"id":"U_kgDOCNoU5Q","is_bot":false,"login":"Alexander-Reyes9","name":"AlexanderReyes99"},"headRefName":"ar-UCSBOrganization-backend","number":63,"title":"Add Backend CRUD API for UCSBOrganization","url":"https://github.com/ucsb-cs156-s26/team02-s26-07/pull/63"},{"author":{"id":"U_kgDOCM7Txw","is_bot":false,"login":"HHYwalktimeSB","name":"Hanson Hu"},"headRefName":"hanson_hu","number":62,"title":"Copy articles and its tests from team01","url":"https://github.com/ucsb-cs156-s26/team02-s26-07/pull/62"}]
